<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Sun Feb 16 2025 14:09:13 GMT+0100 (Central European Standard Time)). */
return array(
	'src/public/dist/admin.js' => '9409dbfab335061927861d74e7dcfa9b',
	'src/public/dist/frontend.js' => '5499447ec365e2ca4dd863963a63168f',
	'src/public/dist/index.js' => '3cb9f0bab73a63db0af5b221d05adf83',
	'src/public/dist/vendor-admin.js' => '17775bc786b6f3a81e572dc7df3a12f6',
	'src/public/dist/vendor-frontend.js' => '2c77f5134932386b2d1a7c75a1014c60',
	'src/public/dist/admin.css' => 'd5634ca7bba3ddff9161360395e4a411',
	'src/public/dist/frontend.css' => 'f4beefb1a69f6e9e1ea886dc9c3dd3fb',
	'src/public/dev/0.js' => 'fcc7956beef7cec7eb14274da98a4f93',
	'src/public/dev/1.js' => '29705f5b0c80680e50800e2b67264809',
	'src/public/dev/admin.js' => '15817a00b1c0cff702219648f1eb18a6',
	'src/public/dev/frontend.js' => '547e87a67d026c986161b32b00ff1b58',
	'src/public/dev/i18n-dir/0.js' => 'fcc7956beef7cec7eb14274da98a4f93',
	'src/public/dev/i18n-dir/1.js' => '29705f5b0c80680e50800e2b67264809',
	'src/public/dev/i18n-dir/admin.js' => '15817a00b1c0cff702219648f1eb18a6',
	'src/public/dev/i18n-dir/frontend.js' => '547e87a67d026c986161b32b00ff1b58',
	'src/public/dev/vendor-admin.js' => '7d4d50693012b6ea70ef4d241be843d6',
	'src/public/dev/vendor-frontend.js' => '08ba79e61f8bd0269ff8e8135ddf0760',
	'src/public/dev/admin.css' => '80b5a0536cea254cd9c080748d1b4188',
	'src/public/dev/frontend.css' => '83cf931282dcf200858ca679e8d49479',
);
