<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Mon Sep 15 2025 20:06:57 GMT+0200 (Mitteleuropäische Sommerzeit)). */
return array(
	'src/public/dist/admin.js' => '53bf0d138d871e775f00cd523c28ea68',
	'src/public/dist/frontend.js' => 'd08005445c88ac320ce83237ed007279',
	'src/public/dist/index.js' => '3cb9f0bab73a63db0af5b221d05adf83',
	'src/public/dist/vendor-admin.js' => 'dae93e20f518e4127d156a6cb929d4c7',
	'src/public/dist/vendor-frontend.js' => '3a1ec9b6239661ee15f290f44f6579ba',
	'src/public/dist/admin.css' => 'de3cc2e8754d5bc5d5631f1a621bdc08',
	'src/public/dist/frontend.css' => '66711f4a952958783d479e01bc16ebf7',
	'src/public/dev/0.js' => 'fcc7956beef7cec7eb14274da98a4f93',
	'src/public/dev/1.js' => '29705f5b0c80680e50800e2b67264809',
	'src/public/dev/admin.js' => '15817a00b1c0cff702219648f1eb18a6',
	'src/public/dev/frontend.js' => '547e87a67d026c986161b32b00ff1b58',
	'src/public/dev/i18n-dir/0.js' => 'fcc7956beef7cec7eb14274da98a4f93',
	'src/public/dev/i18n-dir/1.js' => '29705f5b0c80680e50800e2b67264809',
	'src/public/dev/i18n-dir/admin.js' => '15817a00b1c0cff702219648f1eb18a6',
	'src/public/dev/i18n-dir/frontend.js' => '547e87a67d026c986161b32b00ff1b58',
	'src/public/dev/vendor-admin.js' => '7d4d50693012b6ea70ef4d241be843d6',
	'src/public/dev/vendor-frontend.js' => '08ba79e61f8bd0269ff8e8135ddf0760',
	'src/public/dev/admin.css' => '80b5a0536cea254cd9c080748d1b4188',
	'src/public/dev/frontend.css' => '83cf931282dcf200858ca679e8d49479',
);
